spring:
#  rabbitmq:
#    host: 192.168.30.231
#    port: 5672
#    password: hechaozhen
#    username: hechaozhen
#    virtual-host: hechaozhen
#    requested-heartbeat: 5
#    listener:
#      concurrency: 2
#      max-concurrency: 5
#      acknowledge-mode: manual

  # 数据源
  datasource:
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.40.231:3306/gtwater?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
#      url: jdbc:mysql://192.168.40.231:3306/gtwater_test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC

#  redis:
#    cluster:
#      nodes:
#        - 192.168.0.108:7000
#        - 192.168.0.108:7001
#        - 192.168.0.108:7002
#        - 192.168.0.108:7003
#        - 192.168.0.108:7004
#        - 192.168.0.108:7005
#      max-redirects: 10
#      timeout: 5000
#      max-total: 300
#      max-idle: 20
#      max-wait-millis: 1000
#      test-on-borrow: true
#      test-on-return: true
##      db-index: 1
  redis:
    database: 13
    host: 192.168.40.232
    port: 6379
    password:
    max-total: 5
    max-idle: 8
    min-idle: 2
    max-active: 300
    max-wait: -1
    max-wait-millis: 1000
    test-on-borrow: true
    test-on-return: true
  custom:
    test: a
  dubbo:
    registry:
#      address: zookeeper://192.168.1.100:2181
      address: zookeeper://192.168.40.231:2181
    protocol:
      name: dubbo
      port: 20883
    application:
      qos:
        port: 33333
      id: 1
      name: wtadmin
    base-package: com.gt.manager
encrypt:
  globalKey: 661ee319dff061d4fb6532787f7b6927
  passSalt: w1fsd2DurO0
keyencode:
  DESede: 68EC34C420E6CDA1511A2A40CE94897FA2089EAD6E15D62C

sessionVr:
  duration: 12 #表示小时数
tokenVr:
  duration:  168 #7*24表示天数
webchat:
  h5NetworkUrl: http://127.0.0.1


qrcode:
  url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxca754849de3d4586&redirect_uri=http%3A%2F%2Fwhyvip.viphk1.ngrok.org%2Fwtuser%2Fapiwtuser%2Fpartner%2FaddPartner&response_type=code&scope=snsapi_base&state=
  type: wechat_redirect