spring:
  # 数据源
  datasource:
    username: generalstore
    password: generalstore_2018
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rdsimnan1mdtje1ypp9ph.mysql.rds.aliyuncs.com:3306/generalstore?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
  redis:
    database: 1
    host: 10.170.214.119
    port: 8001
    password: b6df2cd77c63f0f1574^redis
    max-total: 5
    max-idle: 8
    min-idle: 2
    max-active: 300
    max-wait: -1
    max-wait-millis: 1000
    test-on-borrow: true
    test-on-return: true
  custom:
    test: a
  dubbo:
    registry:
      address: zookeeper://10.162.195.153:2881
    protocol:
      name: dubbo
      port: 28883
    application:
      qos:
        port: 33333
      id: 1
      name: wtadmin
    base-package: com.gt.manager
encrypt:
  globalKey: 661ee319dff061d4fb6532787f7b6927
  passSalt: w1fsd2DurO0
keyencode:
  DESede: 68EC34C420E6CDA1511A2A40CE94897FA2089EAD6E15D62C

sessionVr:
  duration: 12 #表示小时数
tokenVr:
  duration:  168 #7*24表示天数
webchat:
  h5NetworkUrl: http://127.0.0.1


qrcode:
  type: wechat_redirect
  url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx5fe899e6a4ffb49d&redirect_uri=http%3A%2F%2Fgeneralstore.gtexpress.cn%2Fwtuser%2Fapiwtuser%2Fpartner%2FaddPartner&response_type=code&scope=snsapi_base&state=