spring:
  datasource:
    username: generalstore
    password: generalstore_2018
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rdsimnan1mdtje1ypp9ph.mysql.rds.aliyuncs.com:3306/generalstore?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
  redis:
    database: 1
    host: 10.170.214.119
    port: 8001
    password: b6df2cd77c63f0f1574^redis
    max-total: 5
    max-idle: 2
    min-idle: 2
    max-active: 5
    max-wait: -1
    max-wait-millis: 1000
    test-on-borrow: true
    test-on-return: true
  custom:
    test: a
encrypt:
  globalKey: 661ee319dff061d4fb6532787f7b6927
  passSalt: w1fsd2DurO0
keyencode:
  DESede: 68EC34C420E6CDA1511A2A40CE94897FA2089EAD6E15D62C

sessionVr:
  duration: 12 #表示小时数
tokenVr:
  duration:  168 #7*24表示天数
webchat:
  h5NetworkUrl: http://p.jinjixiadan.com
wx:
  appId: wx5fe899e6a4ffb49d
  appSecret: d59f0a933f4f4aba59aed205db3bd659
  index_url: http://generalstore.gtexpress.cn/gtwater/index.html#/static/home/index  #商城首页url
  partner_url: http://generalstore.gtexpress.cn/gtwater/index.html#/static/registrationPartners  #合伙人注册页面url
  error_url: http://generalstore.gtexpress.cn/gtwater/index.html#/static/home/index  #error页面